UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '谷口', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4116' AND status = '未架電';
UPDATE call_records SET status_is = '架電対象外', call_count = 1, staff_is = '小林', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4149' AND status = '未架電';
UPDATE call_records SET status_is = '失注', result_contact_status = '通電', call_count = 1, staff_is = '小林', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4150' AND status = '未架電';
UPDATE call_records SET status_is = '失注', result_contact_status = '通電', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4153' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '不通', call_count = 2, last_called_date = '2025-05-02', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4154' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '谷口', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4156' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '不通', call_count = 2, last_called_date = '2025-05-02', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4171' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '不通', call_count = 2, last_called_date = '2025-05-02', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4175' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '不通', call_count = 2, last_called_date = '2025-05-02', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4185' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '通電', call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4227' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', result_contact_status = '通電', call_count = 1, staff_is = '平澤', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4261' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '平澤', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4266' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '通電', call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3592' AND status = '未架電';
UPDATE call_records SET status_is = '失注', result_contact_status = '通電', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3593' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3597' AND status = '未架電';
UPDATE call_records SET status_is = '失注', result_contact_status = '通電', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3598' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '不通', call_count = 1, last_called_date = '2025-04-30', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3602' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', result_contact_status = '通電', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3615' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3616' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '谷口', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3617' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3619' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3623' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3626' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '不通', call_count = 1, last_called_date = '2025-04-30', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3639' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '谷口', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3642' AND status = '未架電';
UPDATE call_records SET result_contact_status = '不通', call_count = 1, last_called_date = '2025-04-25', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3648' AND status = '未架電';
UPDATE call_records SET result_contact_status = '不通', call_count = 1, last_called_date = '2025-04-15', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3652' AND status = '未架電';
UPDATE call_records SET status_is = '失注', result_contact_status = '通電', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3655' AND status = '未架電';
UPDATE call_records SET result_contact_status = '不通', call_count = 1, last_called_date = '2025-04-30', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3658' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '谷口', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3659' AND status = '未架電';
UPDATE call_records SET status_is = '失注', result_contact_status = '通電', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3662' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3664' AND status = '未架電';
UPDATE call_records SET result_contact_status = '不通', call_count = 1, last_called_date = '2025-04-25', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3668' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '不通', call_count = 1, last_called_date = '2025-04-25', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3670' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '通電', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3674' AND status = '未架電';
UPDATE call_records SET status_is = '失注', result_contact_status = '通電', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3682' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '谷口', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3683' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3698' AND status = '未架電';
UPDATE call_records SET result_contact_status = '不通', call_count = 1, last_called_date = '2025-04-25', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3699' AND status = '未架電';
UPDATE call_records SET result_contact_status = '不通', call_count = 1, last_called_date = '2025-04-25', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3704' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '通電', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3692' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3703' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', result_contact_status = '通電', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3708' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '通電', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3710' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3712' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3715' AND status = '未架電';
UPDATE call_records SET result_contact_status = '不通', call_count = 1, last_called_date = '2025-04-30', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3718' AND status = '未架電';
UPDATE call_records SET result_contact_status = '不通', call_count = 2, last_called_date = '2025-04-30', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3721' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3726' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3727' AND status = '未架電';