UPDATE call_records SET status_is = '04.失注', result_contact_status = '不通', call_count = 1, last_called_date = '2025-04-25', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3729' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3736' AND status = '未架電';
UPDATE call_records SET result_contact_status = '不通', call_count = 1, last_called_date = '2025-04-25', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3737' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', result_contact_status = '通電', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3738' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '谷口', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3744' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', result_contact_status = '通電', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3746' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3747' AND status = '未架電';
UPDATE call_records SET result_contact_status = '不通', call_count = 2, last_called_date = '2025-05-01', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3749' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', result_contact_status = '通電', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3750' AND status = '未架電';
UPDATE call_records SET result_contact_status = '不通', call_count = 1, last_called_date = '2025-04-25', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3756' AND status = '未架電';
UPDATE call_records SET result_contact_status = '不通', call_count = 1, last_called_date = '2025-04-25', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3763' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3773' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '通電', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3774' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '通電', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3778' AND status = '未架電';
UPDATE call_records SET result_contact_status = '不通', call_count = 1, last_called_date = '2025-04-25', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3787' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '通電', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3794' AND status = '未架電';
UPDATE call_records SET status_is = '90. 失注', result_contact_status = '通電', call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3796' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '通電', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3804' AND status = '未架電';
UPDATE call_records SET result_contact_status = '不通', call_count = 1, last_called_date = '2025-04-25', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3806' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3809' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '不通', call_count = 1, last_called_date = '2025-04-25', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3811' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '通電', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3812' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '通電', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3826' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '通電', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3832' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '通電', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3833' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', result_contact_status = '通電', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3834' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '畠中', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3837' AND status = '未架電';
UPDATE call_records SET status_is = '失注', result_contact_status = '通電', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3842' AND status = '未架電';
UPDATE call_records SET status_is = '失注', result_contact_status = '通電', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3843' AND status = '未架電';
UPDATE call_records SET status_is = '失注', result_contact_status = '通電', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3848' AND status = '未架電';
UPDATE call_records SET status_is = '失注', result_contact_status = '通電', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3851' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '通電', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3858' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3864' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '不通', call_count = 2, last_called_date = '2025-04-25', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3865' AND status = '未架電';
UPDATE call_records SET status_is = '失注', result_contact_status = '通電', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3866' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '通電', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3867' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '畠中', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3868' AND status = '未架電';
UPDATE call_records SET status_is = '失注', result_contact_status = '通電', call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3869' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3870' AND status = '未架電';
UPDATE call_records SET result_contact_status = '不通', call_count = 2, last_called_date = '2025-05-02', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3873' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '通電', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3876' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '不通', call_count = 1, last_called_date = '2025-05-02', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3879' AND status = '未架電';
UPDATE call_records SET status_is = '失注', result_contact_status = '通電', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3880' AND status = '未架電';
UPDATE call_records SET status_is = '失注', result_contact_status = '通電', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3881' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '不通', call_count = 1, last_called_date = '2025-04-23', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3883' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '不通', call_count = 2, last_called_date = '2025-05-02', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3884' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '不通', call_count = 2, last_called_date = '2025-05-02', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3891' AND status = '未架電';
UPDATE call_records SET result_contact_status = '不通', call_count = 2, last_called_date = '2025-05-02', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3893' AND status = '未架電';
UPDATE call_records SET result_contact_status = '不通', call_count = 1, last_called_date = '2025-04-22', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3903' AND status = '未架電';
UPDATE call_records SET status_is = '失注', result_contact_status = '通電', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3905' AND status = '未架電';