UPDATE call_records SET call_count = 1, last_called_date = '2025-04-18', staff_is = '小林', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3739' AND status = '未架電';
UPDATE call_records SET call_count = 1, last_called_date = '2025-04-18', staff_is = '小林', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3741' AND status = '未架電';
UPDATE call_records SET result_contact_status = '未通', call_count = 1, last_called_date = '2025-04-15', staff_is = '小林', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3742' AND status = '未架電';
UPDATE call_records SET result_contact_status = '未通', call_count = 1, last_called_date = '2025-04-15', staff_is = '小林', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3745' AND status = '未架電';
UPDATE call_records SET status_is = '失注', result_contact_status = '通電', call_count = 1, last_called_date = '2025-04-28', staff_is = '加藤', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3748' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '不通', call_count = 1, last_called_date = '2025-04-24', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3752' AND status = '未架電';
UPDATE call_records SET status_is = '失注', result_contact_status = '通電', call_count = 1, staff_is = '加藤', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3753' AND status = '未架電';
UPDATE call_records SET status_is = '失注', result_contact_status = '通電', call_count = 1, staff_is = '加藤', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3754' AND status = '未架電';
UPDATE call_records SET call_count = 1, last_called_date = '2025-04-18', staff_is = '小林', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3755' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', call_count = 1, last_called_date = '2025-04-18', staff_is = '小林', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3757' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '通電', call_count = 1, staff_is = '加藤', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3759' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3760' AND status = '未架電';
UPDATE call_records SET result_contact_status = '未通', call_count = 2, last_called_date = '2025-05-01', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3761' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3765' AND status = '未架電';
UPDATE call_records SET result_contact_status = '未通', call_count = 2, last_called_date = '2025-05-01', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3766' AND status = '未架電';
UPDATE call_records SET call_count = 1, last_called_date = '2025-04-18', staff_is = '小林', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3767' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '通電', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3768' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '通電', call_count = 1, staff_is = '加藤', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3769' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '通電', call_count = 1, staff_is = '加藤', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3770' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3776' AND status = '未架電';
UPDATE call_records SET result_contact_status = '未通', call_count = 2, last_called_date = '2025-05-01', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3777' AND status = '未架電';
UPDATE call_records SET result_contact_status = '不通', call_count = 2, last_called_date = '2025-05-01', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3779' AND status = '未架電';
UPDATE call_records SET result_contact_status = '未通', call_count = 1, last_called_date = '2025-04-15', staff_is = '小林', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3780' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', call_count = 1, last_called_date = '2025-04-18', staff_is = '小林', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3781' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '通電', call_count = 1, staff_is = '加藤', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3782' AND status = '未架電';
UPDATE call_records SET result_contact_status = '未通', call_count = 2, last_called_date = '2025-05-01', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3783' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '通電', call_count = 1, staff_is = '加藤', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3784' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', result_contact_status = '通電', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3788' AND status = '未架電';
UPDATE call_records SET status_is = '途中で切られた', result_contact_status = '通電', call_count = 1, staff_is = '加藤', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3792' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '通電', call_count = 1, staff_is = '加藤', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3800' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3801' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '通電', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3807' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '通電', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3808' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '通電', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3814' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '通電', call_count = 1, last_called_date = '2025-04-16', staff_is = '小林', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3831' AND status = '未架電';
UPDATE call_records SET result_contact_status = '未通電', call_count = 3, last_called_date = '2025-05-01', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3846' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '通電', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3850' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '不通', call_count = 1, last_called_date = '2025-04-30', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3862' AND status = '未架電';
UPDATE call_records SET result_contact_status = '未通電', call_count = 2, last_called_date = '2025-05-01', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3874' AND status = '未架電';
UPDATE call_records SET status_is = '失注', result_contact_status = '通電', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3888' AND status = '未架電';
UPDATE call_records SET status_is = '失注', result_contact_status = '通電', call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3895' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '不通', call_count = 2, last_called_date = '2025-04-25', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3897' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '通電', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3901' AND status = '未架電';
UPDATE call_records SET status_is = '失注', result_contact_status = '通電', call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3915' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '不通', call_count = 2, last_called_date = '2025-05-02', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3931' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3945' AND status = '未架電';
UPDATE call_records SET result_contact_status = '未通電', call_count = 1, staff_is = '小林', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3996' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '谷口', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM3999' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '通電', call_count = 1, last_called_date = '2025-05-20', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4109' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4113' AND status = '未架電';