UPDATE call_records SET status_is = '07.既存顧客', result_contact_status = '通電', call_count = 1, staff_is = '平澤', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4228' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4237' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '平澤', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4238' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', result_contact_status = '通電', call_count = 1, staff_is = '平澤', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4242' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', result_contact_status = '通電', call_count = 1, staff_is = '平澤', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4244' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4247' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4249' AND status = '未架電';
UPDATE call_records SET status_is = '失注', result_contact_status = '通電', call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4254' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4260' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4264' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '平澤', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4265' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4267' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4270' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '谷口', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4271' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4276' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '谷口', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4277' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4281' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '谷口', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4283' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4285' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', result_contact_status = '通電', call_count = 1, staff_is = '平澤', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4287' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4293' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4296' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4298' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '平澤', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4299' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '通電', call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4300' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4302' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4305' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '平澤', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4307' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4316' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '平澤', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4321' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '平澤', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4323' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4326' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', result_contact_status = '通電', call_count = 1, staff_is = '平澤', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4327' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4328' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4330' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '平澤', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4333' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4334' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4340' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4341' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '平澤', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4342' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4344' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4345' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4348' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4350' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4355' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4357' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4359' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4360' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4363' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4366' AND status = '未架電';