BEGIN;

UPDATE call_records SET status_is = '07.既存顧客', result_contact_status = '通電', call_count = 1, staff_is = '平澤', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4228' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4237' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '平澤', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4238' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', result_contact_status = '通電', call_count = 1, staff_is = '平澤', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4242' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', result_contact_status = '通電', call_count = 1, staff_is = '平澤', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4244' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4247' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4249' AND status = '未架電';
UPDATE call_records SET status_is = '失注', result_contact_status = '通電', call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4254' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4260' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4264' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '平澤', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4265' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4267' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4270' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '谷口', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4271' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4276' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '谷口', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4277' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4281' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '谷口', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4283' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4285' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', result_contact_status = '通電', call_count = 1, staff_is = '平澤', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4287' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4293' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4296' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4298' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '平澤', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4299' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '通電', call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4300' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4302' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4305' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '平澤', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4307' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4316' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '平澤', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4321' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '平澤', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4323' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4326' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', result_contact_status = '通電', call_count = 1, staff_is = '平澤', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4327' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4328' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4330' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '平澤', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4333' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4334' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4340' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4341' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '平澤', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4342' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4344' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4345' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4348' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4350' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4355' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4357' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4359' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4360' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4363' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4366' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4380' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4385' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4390' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4394' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4396' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4406' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4407' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4409' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4410' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4412' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4421' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4432' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4436' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4437' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4438' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4439' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4440' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4441' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4443' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4446' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4447' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4448' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4449' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4451' AND status = '未架電';
UPDATE call_records SET call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4452' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4454' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4457' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4458' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4462' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4464' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4465' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4466' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4467' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4469' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4474' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4478' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4479' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4480' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4485' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4489' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4492' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4497' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4499' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4500' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4501' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4502' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4503' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4504' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4505' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4508' AND status = '未架電';

COMMIT;