BEGIN;

UPDATE call_records SET status_is = '07.既存顧客', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4509' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4512' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4513' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4514' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4517' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4522' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4525' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4526' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4532' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4563' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4568' AND status = '未架電';
UPDATE call_records SET status_is = '31.トスミス（重複）', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4614' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4616' AND status = '未架電';
UPDATE call_records SET status_is = '失注', result_contact_status = '通電', call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4621' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4622' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4624' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4628' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4655' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4658' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4669' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4671' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4676' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4688' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', call_count = 1, staff_is = '小林', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4701' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', call_count = 1, staff_is = '小林', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4703' AND status = '未架電';
UPDATE call_records SET status_is = '05.対応不可/対象外', result_contact_status = '通電', call_count = 1, staff_is = '沢田', status = '架電中', updated_at = NOW() WHERE lead_id = 'OC0216' AND status = '未架電';
UPDATE call_records SET status_is = '05.対応不可/対象外', result_contact_status = '通電', call_count = 1, staff_is = '沢田', status = '架電中', updated_at = NOW() WHERE lead_id = 'OC0217' AND status = '未架電';

COMMIT;