BEGIN;

UPDATE call_records SET result_contact_status = '不通', call_count = 1, last_called_date = '2025-04-22', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4002' AND status = '未架電';
UPDATE call_records SET call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4003' AND status = '未架電';
UPDATE call_records SET result_contact_status = '不通', call_count = 1, last_called_date = '2025-04-22', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4004' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '不通', call_count = 1, last_called_date = '2025-04-22', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4007' AND status = '未架電';
UPDATE call_records SET call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4010' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '通電', call_count = 1, last_called_date = '2025-05-01', staff_is = '奥谷', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4013' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '不通', call_count = 1, last_called_date = '2025-04-22', staff_is = '奥谷', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4014' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '通電', call_count = 1, last_called_date = '2025-05-01', staff_is = '奥谷', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4015' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '不通', call_count = 1, last_called_date = '2025-04-22', staff_is = '奥谷', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4016' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '不通', call_count = 1, last_called_date = '2025-05-01', staff_is = '奥谷', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4017' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '不通', call_count = 1, last_called_date = '2025-04-22', staff_is = '奥谷', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4018' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '不通', call_count = 1, last_called_date = '2025-04-22', staff_is = '奥谷', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4019' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '不通', call_count = 1, last_called_date = '2025-04-22', staff_is = '奥谷', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4021' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '通電', call_count = 1, last_called_date = '2025-05-01', staff_is = '奥谷', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4023' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '通電', call_count = 1, last_called_date = '2025-05-01', staff_is = '奥谷', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4025' AND status = '未架電';
UPDATE call_records SET result_contact_status = '不通', call_count = 1, last_called_date = '2025-05-01', staff_is = '奥谷', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4026' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '不通', call_count = 1, last_called_date = '2025-04-22', staff_is = '奥谷', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4027' AND status = '未架電';
UPDATE call_records SET status_is = '失注', result_contact_status = '通電', call_count = 1, staff_is = '谷口', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4032' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '不通', call_count = 1, last_called_date = '2025-04-22', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4033' AND status = '未架電';
UPDATE call_records SET call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4037' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '谷口', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4038' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '不通', call_count = 1, last_called_date = '2025-04-22', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4039' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '不通', call_count = 1, last_called_date = '2025-04-22', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4040' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4046' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '谷口', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4048' AND status = '未架電';
UPDATE call_records SET result_contact_status = '不通', call_count = 1, last_called_date = '2025-04-22', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4052' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '不通', call_count = 1, last_called_date = '2025-04-30', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4054' AND status = '未架電';
UPDATE call_records SET result_contact_status = '不通', call_count = 1, last_called_date = '2025-04-22', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4056' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '谷口', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4057' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '不通', call_count = 1, last_called_date = '2025-04-22', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4058' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '谷口', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4060' AND status = '未架電';
UPDATE call_records SET result_contact_status = '不通', call_count = 2, last_called_date = '2025-05-01', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4064' AND status = '未架電';
UPDATE call_records SET result_contact_status = '不通', call_count = 2, last_called_date = '2025-05-01', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4065' AND status = '未架電';
UPDATE call_records SET result_contact_status = '不通', call_count = 2, last_called_date = '2025-05-01', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4068' AND status = '未架電';
UPDATE call_records SET result_contact_status = '不通', call_count = 2, last_called_date = '2025-05-01', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4070' AND status = '未架電';
UPDATE call_records SET result_contact_status = '不通', call_count = 1, last_called_date = '2025-04-22', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4071' AND status = '未架電';
UPDATE call_records SET result_contact_status = '不通', call_count = 1, last_called_date = '2025-04-22', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4075' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '通電', call_count = 1, last_called_date = '2025-04-30', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4077' AND status = '未架電';
UPDATE call_records SET status_is = '失注', result_contact_status = '通電', call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4083' AND status = '未架電';
UPDATE call_records SET result_contact_status = '不通', call_count = 1, last_called_date = '2025-04-23', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4088' AND status = '未架電';
UPDATE call_records SET result_contact_status = '不通', call_count = 1, last_called_date = '2025-04-23', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4089' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '通電', call_count = 1, last_called_date = '2025-04-24', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4090' AND status = '未架電';
UPDATE call_records SET status_is = '失注', result_contact_status = '通電', call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4091' AND status = '未架電';
UPDATE call_records SET result_contact_status = '通電', call_count = 1, last_called_date = '2025-04-23', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4094' AND status = '未架電';
UPDATE call_records SET status_is = '失注', result_contact_status = '通電', call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4095' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '谷口', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4098' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '不通', call_count = 1, last_called_date = '2025-04-23', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4099' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '不通', call_count = 2, last_called_date = '2025-05-02', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4102' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '通電', call_count = 2, last_called_date = '2025-04-23', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4105' AND status = '未架電';
UPDATE call_records SET result_contact_status = '不通', call_count = 2, last_called_date = '2025-05-02', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4107' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '不通', call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4110' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4111' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '谷口', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4112' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '不通', call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4114' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '不通', call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4115' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4117' AND status = '未架電';
UPDATE call_records SET result_contact_status = '不通', call_count = 1, last_called_date = '2025-04-23', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4118' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4119' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '不通', call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4120' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '未通', call_count = 1, last_called_date = '2025-04-23', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4123' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4125' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4126' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '不通', call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4129' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4130' AND status = '未架電';
UPDATE call_records SET result_contact_status = '不通', call_count = 1, last_called_date = '2025-04-23', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4132' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '通電', call_count = 1, last_called_date = '2025-04-23', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4133' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '谷口', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4134' AND status = '未架電';
UPDATE call_records SET status_is = '31.トスミス（重複）', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4136' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '不通', call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4138' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '谷口', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4139' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4140' AND status = '未架電';
UPDATE call_records SET result_contact_status = '通電', call_count = 1, last_called_date = '2025-04-23', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4145' AND status = '未架電';
UPDATE call_records SET result_contact_status = '不通', call_count = 1, last_called_date = '2025-04-23', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4146' AND status = '未架電';
UPDATE call_records SET status_is = '07.既存顧客', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4148' AND status = '未架電';
UPDATE call_records SET status_is = '失注', result_contact_status = '通電', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4152' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '不通', call_count = 1, last_called_date = '2025-04-23', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4159' AND status = '未架電';
UPDATE call_records SET result_contact_status = '不通', call_count = 1, last_called_date = '2025-04-23', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4161' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '不通', call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4162' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '不通', call_count = 1, last_called_date = '2025-04-23', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4163' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '不通', call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4165' AND status = '未架電';
UPDATE call_records SET status_is = '失注', result_contact_status = '通電', call_count = 1, status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4167' AND status = '未架電';
UPDATE call_records SET result_contact_status = '通電', call_count = 1, last_called_date = '2025-04-23', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4168' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '不通', call_count = 2, last_called_date = '2025-05-12', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4176' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '不通', call_count = 2, last_called_date = '2025-05-12', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4177' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '不通', call_count = 1, last_called_date = '2025-04-23', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4178' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '不通', call_count = 2, last_called_date = '2025-05-12', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4179' AND status = '未架電';
UPDATE call_records SET status_is = '04.失注', result_contact_status = '通電', call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4192' AND status = '未架電';
UPDATE call_records SET result_contact_status = '不通', call_count = 1, last_called_date = '2025-04-23', staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4195' AND status = '未架電';
UPDATE call_records SET call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4197' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '谷口', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4201' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '谷口', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4207' AND status = '未架電';
UPDATE call_records SET status_is = '31.トスミス（重複）', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4210' AND status = '未架電';
UPDATE call_records SET status_is = '06.未通電⑤', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4212' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '谷口', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4213' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '小田', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4214' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '谷口', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4215' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '谷口', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4217' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '谷口', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4221' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '田邊', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4223' AND status = '未架電';
UPDATE call_records SET status_is = '90.失注', result_contact_status = '通電', call_count = 1, staff_is = '谷口', status = '架電中', updated_at = NOW() WHERE lead_id = 'TM4224' AND status = '未架電';

COMMIT;